config/routes.rb
Proyekto::Application.routes.draw do

  post 'users' => 'users#create' #override devise's registration to maintain RESTful interface

  devise_for :users, :maximum_attempts => 3, :unlock_strategy => :time, :unlock_in => 1, :controllers => { :confirmations => 'users/confirmations' }
  
  resources :users
    
  resources :projects do
    get 'overview', :to => 'projects#overview'
    resources :tickets
  end
  
  resources :tickets do
    resources :comments
  end
  
  resources :roles
  
  root :to => "application#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets
  has_and_belongs_to_many :users

  validates_presence_of :name, :description, :status
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :users
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  has_many :comments

  validates_presence_of :name, :description, :status, :priority, :tracker
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :role
  has_many :comments
  has_many :tickets
  has_and_belongs_to_many :projects
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :middle_name, :last_name, :user_name, :birthdate, :admin
  
  def full_name
    "#{self.last_name.capitalize}, #{self.first_name.capitalize} #{}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :get_projects
  
  def index

  end
  
private
  
  def get_projects
    @projects = Project.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def new
    @comment = Comment.new
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to comments_path
    else
      render :new
    end
  end
  
  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to comments_path
    else
      render :edit
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to comments_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :get_projects
  before_filter :get_project, :only => [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end
  
  def show

  end 
  
  def new
    @project = Project.new
  end
  
  def edit

  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end
  
  def update
    if @project.update_attributes(params[:project])
      redirect_to projects_path
    else
      render :edit
    end
  end
  
  def destroy
    @project.destroy

    redirect_to projects_path
  end
  
  
  def overview
    @project = Project.find params[:project_id]
  end
  
private
  
  def get_projects
    @projects = Project.all
  end
  
  def get_project
    @project = Project.find params[:id]
  end
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :get_projects

  def index
    @roles = Role.all
  end
  
  def show
    @role = Role.find(params[:id])
  end 
  
  def new
    @role = Role.new
  end
  
  def edit
    @role = Role.find(params[:id])
  end
  
  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to roles_path
    else
      render :new
    end
  end
  
  def update
    @role = Role.find(params[:id])

    if @role.update_attributes(params[:role])
      redirect_to roles_path
    else
      render :edit
    end
  end
  
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    redirect_to roles_path
  end
  
private
  
  def get_projects
    @projects = Project.all
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :get_projects
  before_filter :get_project, :only => [:index, :create]

  def index
    @tickets = @project.tickets
  end
  
  def show
    @ticket = Ticket.find(params[:id])
  end
  
  def new
    @ticket = Ticket.new
  end
  
  def edit
    @ticket = Ticket.find(params[:id])
  end
  
  def create
    @ticket = @project.tickets.build(params[:ticket])
    @ticket.project_id = current_user.id;
    @tickets = @project.tickets
    
    @ticket.save
  end
  
  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update_attributes(params[:ticket])
      redirect_to projects_path
    else
      render :edit
    end
  end
  
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    redirect_to projects_path
  end
  
private
  
  def get_projects
    @projects = Project.all
  end
  
  def get_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  
  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(params[resource_name])

    if resource.errors.empty?
      set_flash_message(:notice, :send_instructions) if is_navigational_format?
      respond_with resource, :location => users_path
    else
      respond_with_navigational(resource){ render_with_scope :new }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_projects
  before_filter :get_roles, :only => [:new, :edit]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  
  def create
    @user = User.new params[:user]
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_path
    else
      render :edit
    end
  end
 
private
  
  def get_projects
    @projects = Project.all
  end
  
  def get_roles
    @roles = Role.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/application/index.html.erb
<!--<%= link_to "Sign Up", new_user_registration_path%>-->
<div class="grid_12">
<% if not user_signed_in?%>
<div id="sign-in-form"> 
<h1>Sign In</h1>
  <%= form_for("user", :url => user_session_path) do |f| %>
  
    <p><%= f.label :email %>
    <%= f.text_field :email %></p>
    
    
  <p><%= f.label :password %>
  <%= f.password_field :password %></p>
  
  
  <p>
  <%= f.check_box :remember_me, :id => "remember_me"%> Remember Me</p>
  
  
  <%= f.submit 'Sign in' %>
  <% end %>
  <%= link_to "Forgot your password?", new_password_path('user') %>
  </div>
<% else %>
<h1>Hi <%= current_user.first_name %></h1>

What do you want to do:
<br /><%= link_to "User List", users_path %>
<br /><%= link_to "Go to Project List", projects_path %>
<br /><%= link_to "Go to Ticket List", tickets_path %>
<% end %>
</div>

app/views/comments/_form.html.erb
  <p><%= f.label :body %><br />
  <%= f.text_area :body %></p>

  <p><%= f.submit %></p>

app/views/comments/edit.html.erb
<h2>New Comment</h2>

<%= form_for @comment do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/comments/index.html.erb
hello comments index

<table>
  <tr>
    <th width="200">Name</th>
    <th width="200"></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %> | <%= link_to 'Edit', edit_comment_path(comment) %> | <%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= form_for @comment do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/comments/show.html.erb
<p>
  <b>Name:</b>
  <%= @comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyekto | Project Mangement System</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="nav_bg"></div>
  <div id="divider"></div>
  <div class="container_12">
    <div class="grid_12" id="header"> 
      <span id="logo">Proyekto<small>Project Management System</small></span>
      <% if user_signed_in? %>
      <ul id="nav">
        <li><%= link_to "Dashboard", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Roles", roles_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path  %></li>
        <% if not @projects.empty? %>
        <li>
          <select id="project-options-list">
            <option>Choose a Project</option>
            <% @projects.each do |p| %>
            <option value="<%= project_path(p)%>"><%= p.name %></option>
            <% end %>
          </select>  
        </li>
        <% end %>
      </ul>  
      <% end %>
    </div>
    
    <%= yield %>
   
  </div>













</body>
</html>

app/views/projects/_form.html.erb
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>

  <p><%= f.label :description %>
  <%= f.text_field :description %></p>
  
  <p><%= f.label :status %>
  <%=  f.select :status, options_for_select('Active' => 'Active', 'Closed' => 'Closed') %></p>
  


  <p class="submit-button right"><%= f.submit %></p>

app/views/projects/_overview.html.erb
<p><%= project.description %></p>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= form_for @project do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/projects/index.html.erb
Project List

<table class="content_tbl">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr class="<%= cycle("", "even")%>">
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %> | <%= link_to 'Edit', edit_project_path(project) %> | <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= form_for @project do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f, :p => User.all }%>
<% end %>

app/views/projects/overview.js.erb
$(".project_page_content").html("<%= escape_javascript(render :partial => 'overview', :locals => { :project => @project } ) %>").hide().fadeIn();
$("#proj_nav li a").attr("id", "");
$("#proj_nav li a:eq(0)").attr("id", "selected");

app/views/projects/show.html.erb
<div class="grid_12">

<h2><%= @project.name%></h2>

<ul id="proj_nav">

  <li><%= link_to "Overview", project_overview_path(@project), :remote => true, :id => "selected", :remote => true %></li>
  
  <li><%= link_to "Tickets", project_tickets_path(@project), :remote => true %></li>
  
  <li><%= link_to "Create Tickets", new_project_ticket_path(@project), :remote => true %></li>
  
  <li><a href="#">Members</a></li>
  
</ul>
</div>

<div class="clear"></div>



<div class="project_page_content grid_12">
  
  <%= render :partial => 'overview', :locals => { :project => @project }%>
  
</div>

app/views/roles/_form.html.erb
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  
  
<h3>Permissions</h3>



<fieldset>
  <legend> Projects  </legend>
  <ul>
  
    <li><%= f.check_box :project_create %><%= f.label "Create" %></li>
  
    <li><%= f.check_box :project_read %><%= f.label "Read" %></li>
  
    <li><%= f.check_box :project_update %><%= f.label "Update" %></li>

    <li><%= f.check_box :project_delete %><%= f.label "Delete" %></li>
    
   </ul>
</fieldset>

<fieldset>
  <legend> Project Members </legend>
  <ul>
  
    <li><%= f.check_box :member_add %><%= f.label "Add" %></li>
  
    <li><%= f.check_box :member_remove %><%= f.label "Remove" %></li>
    
  </ul>
</fieldset> 


<fieldset>
  <legend> Tickets  </legend>  
  <ul>
  
    <li><%= f.check_box :ticket_create %><%= f.label "Create" %></li>

    <li><%= f.check_box :ticket_read %><%= f.label "Read" %></li>

    <li><%= f.check_box :ticket_update %><%= f.label "Update" %></li>
  
    <li><%= f.check_box :ticket_delete %><%= f.label "Delete" %></li>

    <li><%= f.check_box :ticket_assign %><%= f.label "Assign" %></li>
    
    <li><%= f.check_box :ticket_comment %><%= f.label "Comment" %></li>
    
   </ul>
</fieldset>

<fieldset>
  <legend> Tags  </legend>  
  <ul>
    <li><%= f.check_box :tag_create %><%= f.label "Create" %></li>

    <li><%= f.check_box :tag_read %><%= f.label "Read" %></li>

    <li><%= f.check_box :tag_update %><%= f.label "Update" %></li>

    <li><%= f.check_box :tag_delete %><%= f.label "Delete" %></li>
  </ul>
  
</fieldset>

<p class="submit-button right"><%= f.submit %></p>

app/views/roles/edit.html.erb
<h2>Edit Role</h2>

<%= form_for @role do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/roles/index.html.erb
Role List

<table class="content_tbl">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr class="<%= cycle("", "even")%>">
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %> | <%= link_to 'Edit', edit_role_path(role) %> | <%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h2>New Role</h2>

<%= form_for @role do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/roles/show.html.erb
<p>
  <b>Name:</b>
  <%= @role.name %>
</p>

app/views/tickets/_form.html.erb
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>

  <p><%= f.label :description %>
  <%= f.text_field :description %></p>
  
  <p><%= f.label :status %>
  <%=  f.select :status, options_for_select('Active' => 'Active', 'Closed' => 'Closed') %></p>

  <p><%= f.label :priority %>
  <%=  f.select :priority, options_for_select('Minor' => 'Minor', 'Normal' => 'Normal', 'Major' => 'Major', 'Critical' => 'Critical') %></p>
  
  <p><%= f.label :tracker %>
  <%=  f.select :tracker, options_for_select('Bug' => 'Bug', 'Task' => 'Task') %></p>

  <p class="submit-button right"><%= f.submit %></p>

app/views/tickets/_index.html.erb
<% if not @tickets.empty? %>

<table class="content_tbl">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <%
    klass = ""
    klass = ticket.priority.eql?("Critical") ? "critical" : ""
  %>
  <tr class="<%= cycle("", "even")%> <%= klass %>">
    <td><%= ticket.name %></td>
    <td><%= ticket.description %></td>
    <td><%= link_to 'Show', ticket %> | <%= link_to 'Edit', edit_ticket_path(ticket) %> | <%= link_to 'Destroy', ticket, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% else %>

<p>There are no tickets yet.</p>

<% end %>

app/views/tickets/_new.html.erb
<h3>New Ticket</h3>

<%= form_for ticket, :url => project_tickets_path, :method => :post, :remote => true do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/tickets/create.js.erb
<% if not @ticket.errors.any?%>

$(".project_page_content").html("<%= escape_javascript(render :partial => 'tickets/index', :locals => { :project => @project } ) %>").hide().fadeIn();
$("#proj_nav li a").attr("id", "");
$("#proj_nav li a:eq(1)").attr("id", "selected");

<% else %>
var div_con = "<div id=\"dialog-message\">";

<% @ticket.errors.full_messages.each do |msg| %>
div_con += "<%= msg %><br/>" ;  
<% end %>

div_con += "</div>";
$("body").append(div_con);
$( "#dialog-message" ).dialog({
      title: "Create Ticket Error",
			modal: true,
			buttons: {
				Ok: function() {
					$( this ).dialog( "close" );
					$(this).remove();
				}
			}
		});

<% end %>

app/views/tickets/edit.html.erb
<h2>New Ticket</h2>

<%= form_for @ticket do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/tickets/index.js.erb
$(".project_page_content").html("<%= escape_javascript(render :partial => 'tickets/index', :locals => { :project => @project } ) %>").hide().fadeIn();
$("#proj_nav li a").attr("id", "");
$("#proj_nav li a:eq(1)").attr("id", "selected");

app/views/tickets/new.js.erb
$(".project_page_content").html("<%= escape_javascript(render :partial => 'new', :locals => { :ticket => @ticket } ) %>").hide().fadeIn();
$("#proj_nav li a").attr("id", "");
$("#proj_nav li a:eq(2)").attr("id", "selected");

app/views/tickets/show.html.erb
<p>
  <b>Name:</b>
  <%= @ticket.name %>
</p>

app/views/users/_form.html.erb
  <p><%= f.label :user_name %>
  <%= f.text_field :user_name %></p>

  <p><%= f.label :email %>
  <%= f.email_field :email %></p>

  <p><%= f.label :first_name %>
  <%= f.text_field :first_name %></p>
  
  <p><%= f.label :middle_name %>
  <%= f.text_field  :middle_name %></p>
  
  <p><%= f.label :last_name %>
  <%= f.text_field  :last_name %></p>
  
  <p><%= f.label :admin %>
  <%= f.check_box :admin %></p>

  <p><%= f.label :password %>
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></p>
  
  <% if not @roles.empty? %>
  <div class="form_role">
  <%= f.label "Role"%>
  <%= f.select :role_id, options_from_collection_for_select(@roles, 'id', 'name')%>
  </div>
  <% end %>
  
  <p><%= f.label :birthdate %>
  <%= f.text_field :birthdate %></p>

  <p class="submit-button right"><%= f.submit "Send" %></p>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/users/index.html.erb
USER LIST
<table class="content_tbl">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr class="<%= cycle("", "even") %>">
    <td><%= link_to user.full_name, user %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= form_for @user do |f| %>
  <%= render :partial => 'form', :locals => { :f =>f }%>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>